repos:
  - repo: https://github.com/MarketSquare/robotframework-robocop
    rev: 5.1.0
    hooks:
      - id: robocop
        name: Robocop Linter
        entry: robocop
        language: system
        files: \.robot$