name: First Run

on : push

jobs : 
  scan_syntax:
    # runs-on: self-hosted
    runs-on: ubuntu-latest
    container:
      image: python:3.10

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      # - name: Setup Python
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: "3.10"
      # - name: Install Robocop
      #   run: |
      #     pip install robotframework-robocop
      - name: Install Robocop      #when no robocop on server
        run: pip install robotframework-robocop
      - name: Run Robocop
        run: robocop
      - name: Check dryrun robot
        run: robot --dryrun testcase/.